### ISSUE TITLE
Clean up dictionary files

### ISSUE THREAD

**Issue by RexMorgan** [csteinmetz1/Cinuosity#1]
I'm not sure where you sourced your dictionaries from, but you may want to clean them up.

It was a little shocking when this playlist was generated.
![image](https://user-images.githubusercontent.com/178752/35303624-394d9ede-0058-11e8-8b35-d00ccc6ff2b7.png)

![image](https://user-images.githubusercontent.com/178752/35303780-c7061a44-0058-11e8-9560-58d78d1a02ed.png)

![image](https://user-images.githubusercontent.com/178752/35303753-aea18286-0058-11e8-8b2f-b7308bc78f92.png)

It looks like when you remove an entry, you'd have to then renumber all items after the one you removed?

**Comment by csteinmetz1** [comment]
I sincerely apologize. I was under the impression the dictionaries used for naming playlists were clean. I will be taking down the site and going through and cleaning up the dictionaries to prevent this. Thank you for bringing it to my attention.

**Comment by csteinmetz1** [comment]
I've gone through and cleaned up the core dictionaries and will be using those only going forward.
