### ISSUE TITLE
Website cinuosity.com down?

### ISSUE THREAD

**Issue by JejM** [csteinmetz1/Cinuosity#2]
Most likely not an issue with the app (haven't tried running in linux yet), but the website appears to be down. https://www.isitdownrightnow.com/cinuosity.com.html

**Comment by csteinmetz1** [comment]
Thank you for the notification!
I am looking into the problem and will follow up when the site is back up.

**Comment by csteinmetz1** [comment]
Sorry for the delay. The site should be reachable now from [https://www.cinuosity.com/](https://www.cinuosity.com/).
